// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frscopcecxikitrpklwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyc2NvcGNlY3hpa2l0cnBrbHdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxNjE1OTUsImV4cCI6MjA3NTczNzU5NX0.q9NEDXqigZiNfzX9dPWmenhQe9247wX1ponG6e1gE4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});